export const artists = [
  { name: "Kanye West", value: "5K4W6rqBFWDnAN6FQUkS6x" },
  { name: "Jay-Z", value: "3nFkdlSjzX9mRTtwJOzDYB" },
  { name: "Eminem", value: "7dGJo4pcD2V6oG8kP0tJRR" },
  { name: "Drake", value: "3TVXtAsR1Inumwj472S9r4" },
  { name: "Kendrick Lamar", value: "2YZyLoL8N0Wb9xBt1NhZWg" },
  { name: "Travis Scott", value: "0Y5tJX1MQlPlqiwlOH1tJY" },
  { name: "Nicki Minaj", value: "0hCNtLu0JehylgoiP8L4Gh" },
  { name: "Cardi B", value: "4kYSro6naA4h99UJvo89HB" },
  { name: "Lil Wayne", value: "55Aa2cqylxrFIXC767Z865" },
  { name: "Snoop Dogg", value: "7hJcb9fa4alzcOq3EaNPoG" },
  { name: "50 Cent", value: "3q7HBObVc0L8jNeTe5Gofh" },
  { name: "Future", value: "1RyvyyTE3xzB2ZywiAwp0i" },
  { name: "Post Malone", value: "246dkjvS1zLTtiykXe5h60" },
  { name: "A$AP Rocky", value: "13ubrt8QOOCPljQ2FL1Kca" },
  { name: "J. Cole", value: "6l3HvQ5sa6mXTsMTB19rO5" },
  { name: "Childish Gambino", value: "73sIBHcqh3Z3NyqHKZ7FOL" },
  { name: "Tyler, The Creator", value: "4V8LLVI7PbaPR0K2TGSxFF" },
  { name: "Ice Cube", value: "3Mcii5XWf6E0lrY3Uky4cA" },
  { name: "Megan Thee Stallion", value: "181bsRPaVXVlUKXrxwZfHK" },
  { name: "Doja Cat", value: "5cj0lLjcoR7YOSnhnX0Po5" },
  { name: "Nas", value: "20qISvAhX20dpIbOOzGK3q" },
  { name: "Lil Nas X", value: "7jVv8c5Fj3E9VhNjxT4snq" },
  { name: "21 Savage", value: "1URnnhqYAYcrqrcwql10ft" },
  { name: "Juice WRLD", value: "4MCBfE4596Uoi2O4DtmEMz" },
  { name: "Lil Baby", value: "5f7VJjfbwm532GiveGC0ZK" },
  { name: "Jack Harlow", value: "2LIk90788K0zvyj2JJVwkJ" },
  { name: "Playboi Carti", value: "699OTQXzgjhIYAHMy9RyPD" },
  { name: "Young Thug", value: "50co4Is1HCEo8bhOyUWKpn" },
  { name: "Roddy Ricch", value: "757aE44tKEUQEqRuT6GnEB" },
  { name: "Lil Uzi Vert", value: "4O15NlyKLIASxsJ0PrXPfz" },
  { name: "The Notorious B.I.G.", value: "5me0Irg2ANcsgc93uaYrpb" },
  { name: "Tupac Shakur", value: "0QhGH0GJkrrfNIYmVY7BVi" },
  { name: "Logic", value: "4xRYI6VqpkE3UwrDrAZL8L" },
  { name: "Big Sean", value: "0c173mlxpT3dSFRgMO8XPh" },
  { name: "Wiz Khalifa", value: "137W8MRPWKqSmrBGDBFSop" },
  { name: "Rick Ross", value: "1sBkRIssrMs1AbVkOJbc7a" },
  { name: "Dr. Dre", value: "6DPYiyq5kWVQS4RGwxzPC7" },
  { name: "Anderson .Paak", value: "3jK9MiCrA42lLAdMGUZpwa" },
  { name: "Ice Spice", value: "3LZZPxNDGDFVSIPqf4JuEf" },
  { name: "Stormzy", value: "2SrSdSvpminqmStGELCSNd" },
  { name: "Skepta", value: "2p1fiYHYiXz9qi0JJyxBzN" },
  { name: "Dave", value: "6Ip8FS7vWT1uKkJSweANQK" },
  { name: "DaBaby", value: "4r63FhuTkUYltbVAg5TQnk" },
].sort((a, b) => a.name.localeCompare(b.name));
