export const hometowns = [
  { name: "Chicago, Illinois, USA", value: "Chicago, Illinois, USA" },
  { name: "Brooklyn, New York, USA", value: "Brooklyn, New York, USA" },
  { name: "Detroit, Michigan, USA", value: "Detroit, Michigan, USA" },
  { name: "Toronto, Ontario, Canada", value: "Toronto, Ontario, Canada" },
  { name: "Compton, California, USA", value: "Compton, California, USA" },
  { name: "Houston, Texas, USA", value: "Houston, Texas, USA" },
  { name: "Queens, New York, USA", value: "Queens, New York, USA" },
  { name: "The Bronx, New York, USA", value: "The Bronx, New York, USA" },
  { name: "New Orleans, Louisiana, USA", value: "New Orleans, Louisiana, USA" },
  { name: "Long Beach, California, USA", value: "Long Beach, California, USA" },
  { name: "Atlanta, Georgia, USA", value: "Atlanta, Georgia, USA" },
  { name: "Syracuse, New York, USA", value: "Syracuse, New York, USA" },
  { name: "Harlem, New York, USA", value: "Harlem, New York, USA" },
  { name: "Fayetteville, North Carolina, USA", value: "Fayetteville, North Carolina, USA" },
  { name: "Stone Mountain, Georgia, USA", value: "Stone Mountain, Georgia, USA" },
  { name: "Ladera Heights, California, USA", value: "Ladera Heights, California, USA" },
  {
    name: "South Central Los Angeles, California, USA",
    value: "South Central Los Angeles, California, USA",
  },
  { name: "Los Angeles, California, USA", value: "Los Angeles, California, USA" },
  { name: "Lithia Springs, Georgia, USA", value: "Lithia Springs, Georgia, USA" },
  { name: "Louisville, Kentucky, USA", value: "Louisville, Kentucky, USA" },
  { name: "Philadelphia, Pennsylvania, USA", value: "Philadelphia, Pennsylvania, USA" },
  { name: "New York City, New York, USA", value: "New York City, New York, USA" },
  { name: "Gaithersburg, Maryland, USA", value: "Gaithersburg, Maryland, USA" },
  { name: "Minot, North Dakota, USA", value: "Minot, North Dakota, USA" },
  { name: "Miami, Florida, USA", value: "Miami, Florida, USA" },
  { name: "Oxnard, California, USA", value: "Oxnard, California, USA" },
  { name: "Croydon, London, England", value: "Croydon, London, England" },
  { name: "Tottenham, London, England", value: "Tottenham, London, England" },
  { name: "Streatham, London, England", value: "Streatham, London, England" },
  { name: "Cleveland, Ohio, USA", value: "Cleveland, Ohio, USA" },
];
